spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8889/chatting?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #default_batch_fetch_size: 2
